/* CavaPasMarcher — API bridge with dynamic bearer authentication. */
(function () {
  const API = window.CPM_API_URL || 'http://localhost:8787/api'; const $ = (id) => document.getElementById(id); const value = (id) => $(id)?.value?.trim() || '';
  const getToken = () => window.CPMAuth?.token?.() || window.CPM_API_TOKEN || localStorage.getItem('cpm-session-token') || '';
  const toast = (message) => { const el = $('toast'); if (!el) return; el.textContent = message; el.classList.add('show'); window.setTimeout(() => el.classList.remove('show'), 2800); };
  const headers = (json = false) => ({ ...(json ? {'content-type':'application/json'} : {}), ...(getToken() ? { authorization:`Bearer ${getToken()}` } : {}) });
  const request = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { ...options, headers:{ ...headers(Boolean(options.body)), ...(options.headers || {}) } }); if (!response.ok) throw new Error(`API ${response.status}`); return response; };
  const local = () => { try { return JSON.parse(localStorage.getItem('cpm-last-project') || 'null'); } catch { return null; } };
  const brief = () => ({ name:value('gen-name'), sector:value('gen-sector'), country:value('gen-country') || 'FR', city:value('gen-city'), plan:value('gen-plan') || 'pro', language:value('gen-language') || 'fr', languages:[...document.querySelectorAll('#language-checks input:checked')].map((input) => input.value), description:value('gen-description'), goal:value('brief-goal') || value('gen-goal'), offer:value('brief-offer'), audience:value('brief-audience'), phone:value('brief-phone'), email:value('brief-email'), address:value('brief-address') });
  async function save() { const data = brief(); if (!data.name || !data.sector) return; const old = local(); try { const path = old?.id ? `/projects/${encodeURIComponent(old.id)}` : '/projects'; const response = await request(path, { method:old?.id ? 'PUT' : 'POST', body:JSON.stringify(data) }); const saved = await response.json(); localStorage.setItem('cpm-last-project', JSON.stringify(saved)); const html = window.CPMGeneratedSite?.html; if (html && saved.id) { await request(`/projects/${saved.id}/site`, { method:'PUT', body:JSON.stringify({html}) }); await request(`/projects/${saved.id}/versions`, { method:'POST', body:JSON.stringify({html, name:data.name, project:{...data, pricing:saved.pricing}}) }); } toast('Projet, site et version enregistrés.'); } catch { localStorage.setItem('cpm-last-project', JSON.stringify({...data, site:window.CPMGeneratedSite?.html ? {html:window.CPMGeneratedSite.html} : undefined, localOnly:true})); toast('API indisponible — sauvegarde locale active.'); } }
  document.addEventListener('click', (event) => { if (event.target.closest('#generate-site')) window.setTimeout(save, 250); });
  window.CPMProjects = { all:async() => (await request('/projects')).json().then((data) => data.projects || []), get:async(id) => (await request(`/projects/${encodeURIComponent(id)}`)).json(), remove:async(id) => { await request(`/projects/${encodeURIComponent(id)}`, {method:'DELETE'}); }, update:async(id, data) => (await request(`/projects/${encodeURIComponent(id)}`, {method:'PUT',body:JSON.stringify(data)})).json(), saveSite:async(id, html) => (await request(`/projects/${encodeURIComponent(id)}/site`, {method:'PUT',body:JSON.stringify({html})})).json(), versions:async(id) => (await request(`/projects/${encodeURIComponent(id)}/versions`)).json().then((data) => data.versions || []), version:async(id, versionId) => (await request(`/projects/${encodeURIComponent(id)}/versions/${encodeURIComponent(versionId)}`)).json(), restoreVersion:async(id, versionId) => (await request(`/projects/${encodeURIComponent(id)}/versions/${encodeURIComponent(versionId)}/restore`, {method:'POST'})).json(), saveVersion:async(id, data) => (await request(`/projects/${encodeURIComponent(id)}/versions`, {method:'POST',body:JSON.stringify(data)})).json() };
})();
