import http from 'node:http';
import { randomUUID, timingSafeEqual } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { authenticate, login, logout, register } from './auth.js';
import { getProspects, createProspect, updateProspect, deleteProspect, analyzeWebsite, scoreProspect } from './prospects.js';
import { getQuotes, createQuote, updateQuote, deleteQuote, getQuoteHTML } from './quotes.js';

const root = dirname(fileURLToPath(import.meta.url)); const dataFile = process.env.CPM_DATA_FILE || join(root, 'data', 'projects.json'); const port = Number(process.env.PORT || 8787); const max = 2 * 1024 * 1024;
const origin = process.env.CPM_ALLOWED_ORIGIN || '*'; const legacyToken = process.env.CPM_AUTH_TOKEN || ''; const rate = new Map();
const currencies = { FR:'EUR',BE:'EUR',DE:'EUR',ES:'EUR',IT:'EUR',PT:'EUR',NL:'EUR',MA:'MAD',DZ:'DZD',TN:'TND',EG:'EGP',SN:'XOF',CI:'XOF',CM:'XAF',NG:'NGN',ZA:'ZAR',CH:'CHF',GB:'GBP',US:'USD',CA:'CAD',MX:'MXN',BR:'BRL',AU:'AUD',JP:'JPY',CN:'CNY',IN:'INR',KR:'KRW',SG:'SGD',NZ:'NZD',AE:'AED',SA:'SAR',TR:'TRY',AR:'ARS',CL:'CLP',CO:'COP' };
const json = (res,status,body) => { res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'*'}); res.end(JSON.stringify(body)); };
const safeEqual = (a,b) => { const x=Buffer.from(a), y=Buffer.from(b); return x.length===y.length && timingSafeEqual(x,y); };
function legacy(req) { if (!legacyToken) return false; const value=String(req.headers.authorization||''); return value.startsWith('Bearer ') && safeEqual(value.slice(7).trim(),legacyToken); }
function limited(req) { const key=req.socket.remoteAddress||'unknown'; const now=Date.now(); const item=rate.get(key); if (!item || now-item.started>60000) { rate.set(key,{started:now,count:1}); return true; } if(item.count>=30) return false; item.count++; return true; }
async function load() { try { const value=JSON.parse(await readFile(dataFile,'utf8')); return Array.isArray(value)?value:[]; } catch { return []; } } async function save(value) { await mkdir(dirname(dataFile),{recursive:true}); const temp=`${dataFile}.tmp.${Date.now()}`; await writeFile(temp,JSON.stringify(value,null,2)); await writeFile(dataFile,JSON.stringify(value,null,2)); }
async function body(req) { let size=0; const chunks=[]; for await (const chunk of req) { size+=chunk.length; if(size>max) throw Object.assign(new Error('payload too large'),{status:413}); chunks.push(chunk); } return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'); }
function pricing(country='FR',sector='',plan='basic') { const currency=currencies[String(country).toUpperCase().slice(0,2)]||'USD'; const values={landing:{setup:1900,monthly:99},medium:{setup:3900,monthly:179},basic:{setup:2900,monthly:149},pro:{setup:6900,monthly:290},ultimate:{setup:18900,monthly:690}}[plan]||{setup:2900,monthly:149}; const boost=/restaurant|hôtel|hotel|médecin|avocat|finance|immobilier|cabinet|clinique|santé|health|legal|finance|real|estate/i.test(sector)?1.2:1.08; return {currency,setup:Math.round(values.setup*boost),monthly:Math.round(values.monthly*boost)}; }
function valid(value) { if(!value||typeof value!=='object'||Array.isArray(value)) return 'Invalid JSON object'; if(!String(value.name||'').trim()) return 'name is required'; if(!String(value.sector||'').trim()) return 'sector is required'; return null; }
function project(input,previous={},userId) { const now=new Date().toISOString(); const plan=String(input.plan||previous.plan||'basic').toLowerCase(); const country=String(input.country||previous.country||'FR').toUpperCase(); const text=(value,fallback='',limit=500)=>String(value??fallback).trim().slice(0,limit); const p=pricing(country,input.sector,plan); return {id:previous.id||randomUUID(),ownerId:userId,name:text(input.name,previous.name,160),sector:text(input.sector,previous.sector,160),country,city:text(input.city,previous.city,160),plan,language:text(input.language,previous.language||'fr',12),languages:Array.isArray(input.languages)?input.languages.map((value)=>text(value,'',12)).filter(Boolean).slice(0,12):(previous.languages||[]),description:text(input.description,previous.description,4000),goal:text(input.goal,previous.goal,300),offer:text(input.offer,previous.offer,500),audience:text(input.audience,previous.audience,500),phone:text(input.phone,previous.phone,80),email:text(input.email,previous.email,240),address:text(input.address,previous.address,500),color:text(input.color,previous.color||'auto',32),pricing:p,site:input.site||previous.site||null,versions:input.versions||previous.versions||[],createdAt:previous.createdAt||now,updatedAt:now}; }
function publicProject(value) { const {versions,ownerId,...rest}=value; return {...rest,versionCount:Array.isArray(versions)?versions.length:0}; }
async function userFor(req) { if (legacy(req)) return { id:'legacy-admin', role:'admin' }; return authenticate(req); }
async function handler(req,res) { if(req.method==='OPTIONS') return json(res,204,{}); const url=new URL(req.url,`http://${req.headers.host||'localhost'}`); if(req.method==='GET'&&url.pathname==='/api/health') return json(res,200,{status:'ok',time:new Date().toISOString()});
  if(!limited(req)) return json(res,429,{error:'rate limit exceeded'});
  if(req.method==='POST'&&url.pathname==='/api/auth/register') { try { const result=await register(await body(req)); return json(res,201,result); } catch(e) { return json(res,e.status||500,{error:e.message}); } }
  if(req.method==='POST'&&url.pathname==='/api/auth/login') { try { return json(res,200,await login(await body(req))); } catch(e) { return json(res,e.status||500,{error:e.message}); } }
  if(req.method==='POST'&&url.pathname==='/api/auth/logout') { const header=String(req.headers.authorization||''); logout(header.startsWith('Bearer ')?header.slice(7):''); return json(res,204,{}); }
  const user=await userFor(req); if(!user) return json(res,401,{error:'authentication required'}); if(req.method==='GET'&&url.pathname==='/api/auth/me') return json(res,200,{user});
  if(req.method==='POST'&&url.pathname==='/api/prospects/analyze') { try { const input=await body(req); const result=await analyzeWebsite(input.url); return json(res,200,result); } catch(e) { return json(res,400,{error:e.message}); } }
  if(req.method==='GET'&&url.pathname==='/api/prospects') { const prospects=await getProspects(user.id); return json(res,200,{prospects}); }
  if(req.method==='POST'&&url.pathname==='/api/prospects') { try { const input=await body(req); const prospect=await createProspect(user.id,input); return json(res,201,prospect); } catch(e) { return json(res,400,{error:e.message}); } }
  const parts=url.pathname.split('/').filter(Boolean);
  if(parts[0]==='api'&&parts[1]==='prospects'&&parts[2]&&parts[3]==='analyze'&&req.method==='POST') { try { const prospect=await getProspects(user.id).then((items)=>items.find((item)=>item.id===parts[2])); if(!prospect) return json(res,404,{error:'prospect not found'}); if(!prospect.website) return json(res,400,{error:'prospect website is required'}); const analysis=await analyzeWebsite(prospect.website); const updated=await updateProspect(user.id,prospect.id,{analysis,status:analysis.score>=60?'analyzed':'new'}); return json(res,200,updated); } catch(e) { return json(res,400,{error:e.message}); } }
  if(parts[0]==='api'&&parts[1]==='prospects'&&parts[2]) { const prospectId=parts[2]; if(req.method==='GET') { const prospect=await getProspects(user.id).then(p=>p.find(x=>x.id===prospectId)); return json(res,prospect?200:404,prospect||{error:'not found'}); } if(req.method==='PUT') { try { const input=await body(req); const updated=await updateProspect(user.id,prospectId,input); return json(res,200,updated); } catch(e) { return json(res,400,{error:e.message}); } } if(req.method==='DELETE') { await deleteProspect(user.id,prospectId); return json(res,204,{}); } }
  if(req.method==='POST'&&url.pathname==='/api/quotes') { try { return json(res,201,await createQuote(user.id,await body(req))); } catch(e) { return json(res,400,{error:e.message}); } }
  if(req.method==='GET'&&url.pathname==='/api/quotes') return json(res,200,{quotes:await getQuotes(user.id)});
  if(parts[0]==='api'&&parts[1]==='quotes'&&parts[2]) {
    const quoteId=parts[2]; const quote=(await getQuotes(user.id)).find((item)=>item.id===quoteId);
    if(req.method==='GET'&&parts[3]==='html') { if(!quote) return json(res,404,{error:'quote not found'}); res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}); return res.end(await getQuoteHTML(quote)); }
    if(req.method==='GET') return json(res,quote?200:404,quote||{error:'quote not found'});
    if(req.method==='PUT') { try { return json(res,200,await updateQuote(user.id,quoteId,await body(req))); } catch(e) { return json(res,404,{error:e.message}); } }
    if(req.method==='DELETE') { await deleteQuote(user.id,quoteId); return json(res,204,{}); }
  }
  if(parts[0]!=='api'||parts[1]!=='projects') return json(res,404,{error:'route not found'}); const projects=await load(); const visible=(item)=>user.role==='admin'||item.ownerId===user.id;
  if(req.method==='GET'&&parts.length===2) return json(res,200,{projects:projects.filter(visible).map(publicProject)});
  if(req.method==='POST'&&parts.length===2) { const input=await body(req), error=valid(input); if(error) return json(res,400,{error}); const created=project(input,{},user.id); projects.unshift(created); await save(projects); return json(res,201,publicProject(created)); }
  const index=projects.findIndex((item)=>item.id===parts[2]&&visible(item)); if(index<0) return json(res,404,{error:'project not found'}); const current=projects[index];
  if(req.method==='GET'&&parts.length===3) return json(res,200,publicProject(current)); if(req.method==='PUT'&&parts.length===3) { const input=await body(req), error=valid(input); if(error) return json(res,400,{error}); projects[index]=project(input,current,user.id); await save(projects); return json(res,200,publicProject(projects[index])); }
  if(req.method==='DELETE'&&parts.length===3) { projects.splice(index,1); await save(projects); return json(res,204,{}); }
  if(parts[3]==='site'&&req.method==='GET') return json(res,200,current.site||{html:null}); if(parts[3]==='site'&&req.method==='PUT') { const input=await body(req); if(typeof input.html!=='string') return json(res,400,{error:'html is required'}); current.site={html:input.html,savedAt:new Date().toISOString()}; await save(projects); return json(res,200,{saved:true}); }
  if(parts[3]==='versions'&&req.method==='GET') return json(res,200,{versions:(current.versions||[]).map(({html,...item})=>item)}); if(parts[3]==='versions'&&req.method==='POST') { const input=await body(req); if(typeof input.html!=='string') return json(res,400,{error:'html is required'}); const version={id:randomUUID(),html:input.html,name:input.name||'Version',savedAt:new Date().toISOString()}; current.versions=[version,...current.versions||[]].slice(0,50); await save(projects); return json(res,201,{id:version.id,name:version.name,savedAt:version.savedAt}); }
  return json(res,404,{error:'route not found'});
}
http.createServer((req,res)=>handler(req,res).catch((error)=>json(res,error.status||500,{error:error.status?error.message:'internal server error'}))).listen(port,()=>console.log(`CavaPasMarcher API server running on http://localhost:${port}`));
